import type { Metadata } from "next";
import "./globals.css";
import RoutingNavbar from "@/uicomponents/shared/Navbar.shared.uicomponents";
import fonts from "@/lib/utils/fonts";


export const metadata: Metadata = {
  title: "Medbloomberg - Your Personal Medical Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.roboto.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <RoutingNavbar />
        {children}
      </body>
    </html>
  );
}
